it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
]

app_name = "task_manager"

templates/includes/footer.html
  <footer class="footer bottom-0 width-100 pt-3 mt-auto ">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Task Manager</h6>
          </div>
          <div>
            <h6 class="mt-2 mb-2 opacity-8">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.linkedin.com/in/lana-chernenko/" target="_blank">
                  <i class="fab fa-linkedin-in text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/loplicat/" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Tasks</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'task_manager:task-list' %}" target="_blank">
                  All tasks
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'task_manager:task-type-list' %}" target="_blank">
                  Task types
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Workers</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'task_manager:worker-list' %}" target="_blank">
                  All workers
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'task_manager:position-list' %}" target="_blank">
                  Positions
                </a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation-light.html
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
  <div class="container">
    <a class="navbar-brand" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
      <img src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      Task Manager
    </a>
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
    </button>
    <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
      <ul class="navbar-nav navbar-nav-hover w-100">
        <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
             id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
            Tasks
            <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
          </a>
          <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
               aria-labelledby="dropdownMenuPages">
            <div class="d-none d-lg-block">
              <a href="{% url "task_manager:task-list" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-thumbtack me-1"></i>
                All tasks
              </a>
              <a href="{% url "task_manager:task-type-list" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-sticky-note me-1"></i>
                Task types
              </a>
              <a href="{% url "task_manager:task-create" %}" class="dropdown-item border-radius-md">
                <i class="fas fa-edit me-1"></i>
                Create task
              </a>
            </div>
            <div class="d-lg-none">
              <a href="{% url "task_manager:task-list" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-thumbtack me-1"></i>
                All tasks
              </a>
              <a href="{% url "task_manager:task-type-list" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-sticky-note me-1"></i>
                Task types
              </a>
              <a href="{% url "task_manager:task-create" %}" class="dropdown-item border-radius-md">
                <i class="fas fa-edit me-1"></i>
                Create task
              </a>
            </div>
          </div>
        </li>
        <li class="nav-item dropdown dropdown-hover mx-2">
          <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
             id="dropdownMenuBlocks" data-bs-toggle="dropdown" aria-expanded="false">
            Workers
            <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
          </a>
          <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
               aria-labelledby="dropdownMenuPages">
            <div class="d-none d-lg-block">
              <a href="{% url "task_manager:worker-list" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-users me-1"></i>
                All workers
              </a>
              <a href="{% url "task_manager:position-list" %}" class="dropdown-item border-radius-md">
                <i class="fas fa-id-badge me-1"></i>
                Positions
              </a>
              <a href="{% url "task_manager:worker-create" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-user-plus me-1"></i>
                Add new worker
              </a>
            </div>
            <div class="d-lg-none">
              <a href="{% url "task_manager:worker-list" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-users me-1"></i>
                All workers
              </a>
              <a href="{% url "task_manager:position-list" %}" class="dropdown-item border-radius-md">
                <i class="fas fa-id-badge me-1"></i>
                Positions
              </a>
              <a href="{% url "task_manager:worker-create" %}" class="dropdown-item border-radius-md">
                <i class="fa fas fa-user-plus me-1"></i>
                Add new worker
              </a>
            </div>
          </div>
        </li>
        <li class="nav-item ms-lg-auto">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="logout-btn">
              <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                <i class="fa fa-sign-out me-1"></i>
                <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                   data-bs-placement="bottom" title="Logout">Logout</p>
              </a>
            </button>
          </form>
        </li>
        <li class="nav-item my-auto ms-3 ms-lg-0">
          <a href="https://github.com/loplicat/it-company-task-manager"
             target="_blank"
             class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">PROJECT ON GITHUB</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
             href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
            <img src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
            Task Manager
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Tasks
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url "task_manager:task-list" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-thumbtack me-1"></i>
                      All tasks
                    </a>
                    <a href="{% url "task_manager:task-type-list" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-sticky-note me-1"></i>
                      Task types
                    </a>
                    <a href="{% url "task_manager:task-create" %}" class="dropdown-item border-radius-md">
                      <i class="fas fa-edit me-1"></i>
                      Create task
                    </a>
                  </div>

                  <div class="d-lg-none">
                    <a href="{% url "task_manager:task-list" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-thumbtack me-1"></i>
                      All tasks
                    </a>
                    <a href="{% url "task_manager:task-type-list" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-sticky-note me-1"></i>
                      Task types
                    </a>
                    <a href="{% url "task_manager:task-create" %}" class="dropdown-item border-radius-md">
                      <i class="fas fa-edit me-1"></i>
                      Create task
                    </a>
                  </div>
                </div>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Workers
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <a href="{% url "task_manager:worker-list" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-users me-1"></i>
                      All workers
                    </a>
                    <a href="{% url "task_manager:position-list" %}" class="dropdown-item border-radius-md">
                      <i class="fas fa-id-badge me-1"></i>
                      Positions
                    </a>
                    <a href="{% url "task_manager:worker-create" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-user-plus me-1"></i>
                      Add new worker
                    </a>
                  </div>

                  <div class="d-lg-none">
                    <a href="{% url "task_manager:worker-list" %}" class="dropdown-item border-radius-md">
                      <i class="fa fas fa-users me-1"></i>
                      All workers
                    </a>
                    <a href="{% url "task_manager:position-list" %}" class="dropdown-item border-radius-md">
                      <i class="fas fa-id-badge me-1"></i>
                      Positions
                    </a>
                    <a href="{% url "task_manager:worker-create" %}" class="dropdown-item border-radius-md">
                      <i class="fa ffas fa-user-plus me-1"></i>
                      Add new worker
                    </a>
                  </div>
                </div>
              </li>

              <li class="nav-item ms-lg-auto">
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="logout-btn">
                    <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                         data-bs-placement="bottom" title="Logout">Logout</p>
                    </a>
                  </button>
                </form>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'task_manager:task-list' %}"
                   target="_blank"
                   class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Get started</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="row text-center py-2">
    <div class="col-auto mx-auto">
      <ul class="pagination pagination-primary m-4">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link"
               href="?{% query_transform request page=page_obj.previous_page_number %}"
               aria-label="Previous">
              <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
            </a>
          </li>
        {% endif %}
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active">
              <span class="page-link">{{ page_obj.number }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link"
                 href="?{% query_transform request page=page_num %}"
                 aria-label="Previous">
                <span>{{ page_num }}</span>
              </a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link"
               href="?{% query_transform request page=page_obj.next_page_number %}"
               aria-label="Next">
              <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/search_form.html
{% load crispy_forms_filters %}
{% load static %}
<div class="input-group mt-3 ms-44">
  <form class="form-inline-search" action="" method="get">
    {% csrf_token %}
    {{ search_form|crispy }}
    <button class="btn btn-outline-dark ms-1" id="search-btn" type="submit" value="submit">
      <i class="fa fa fa-search"></i>
    </button>
  </form>
</div>