it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name", ]

    def __str__(self):
        return f"{self.name}"


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name", ]

    def __str__(self):
        return f"{self.name}"


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name="workers",
        null=True,
        blank=True
    )

    def __str__(self):
        return (f"{self.first_name} {self.last_name} "
                f"({self.position.name if self.position else 'no position'})")


class Task(models.Model):

    PRIORITY_CHOICES = (
        ("Urgent", "Urgent"),
        ("High-priority", "High-priority"),
        ("Medium-priority", "Medium-priority"),
        ("Low-priority", "Low-priority")
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE, related_name="tasks")
    assignees = models.ManyToManyField(Worker, related_name="tasks")

    class Meta:
        ordering = ["deadline", ]

    def __str__(self):
        return self.name

task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from task_manager.models import Position, Worker, Task


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = "__all__"


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position",
        )


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["username", "first_name", "last_name", "email", "position"]


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    deadline = forms.DateField(
        widget=forms.SelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day"),
        )
    )

    class Meta:
        model = Task
        fields = "__all__"


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )

task_manager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    PositionForm,
    TaskForm,
    WorkerCreationForm,
    WorkerUpdateForm,
    TaskTypeSearchForm,
    PositionSearchForm, WorkerSearchForm, TaskSearchForm
)
from task_manager.models import TaskType, Position, Task


@login_required
def index(request):
    """View function for the home page of the site"""
    num_workers = get_user_model().objects.count()
    num_positions = Position.objects.count()
    num_task_types = TaskType.objects.count()

    context = {
        "num_workers": num_workers,
        "num_positions": num_positions,
        "num_task_types": num_task_types,
    }

    return render(request, "task_manager/index.html", context=context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    template_name = "task_manager/task_type_list.html"
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = TaskType.objects.prefetch_related("tasks")
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task_manager:task-type-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Position.objects.prefetch_related("workers")
        form = PositionSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("task_manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = get_user_model().objects.prefetch_related("position")
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    queryset = get_user_model().objects.prefetch_related("tasks")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = WorkerCreationForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("task_manager:worker-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all().prefetch_related("assignees")
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related("assignees")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")

templates/task_manager/position_confirm_delete.html
{% extends 'layouts/base.html' %}

{% block title %} Delete position {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% load crispy_forms_filters %}
{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-12">
          <h3 class="mt-12">Are you sure you want to delete the position: {{ position }}?</h3>
          <p>All workers working in this position will be deleted!</p>
        </div>
      </div>
      <br>
      <div class="row">
        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Yes, delete" class="btn bg-gradient-danger me-4">
          <a class="btn bg-gradient-success ms-4" href="{{ request.META.HTTP_REFERER }}">Changed my mind</a>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/position_form.html
{% extends 'layouts/base.html' %}

{% block title %} {{ object|yesno:"Update,Create" }} task type {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% load crispy_forms_filters %}
{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3 min-height-600">
    <div class="container w-50">
      <div class="row">
        <div class="col-lg-6">
          <h3 class="mt-3">{{ object|yesno:"Update,Create" }} position</h3>
        </div>
      </div>
      <div class="row">
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Save" class="btn bg-gradient-primary btn-lg">
        </form>
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/position_list.html
{% extends 'layouts/base.html' %}

{% block title %} Task List {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <h3>Positions
            <a href="{% url 'task_manager:position-create' %}"
               class="btn btn-outline-success link-to-page ms-3 mt-3">Create position</a>
          </h3>
        </div>
        <div class="col-3">
          {% include "includes/search_form.html" %}
        </div>
      </div>
      <div class="row">
        {% if position_list %}
          {% for position in position_list %}
            <div class="col-lg-3 col-sm-6 my-2">
              <div class="card card-plain card-blog bg-gradient-faded-white">
                <div class="card-body px-0 m-1 mx-3">
                  <h5 class="text-dark font-weight-bold">
                    {{ position.name }}
                  </h5>
                  {% if position.workers.all %}
                    <p class="mb-0"><i class="fas fa-user-friends me-1"></i>Work in this position:</p>
                    {% for worker in position.workers.all %}
                      <a class="py-2" href="{% url 'task_manager:worker-detail' pk=worker.id %}">
                        <u>{{ worker.get_full_name }}</u>{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}
                  {% else %}
                    <p>No one works in this position yet</p>
                  {% endif %}
                  <br>
                  <br>
                  <a class="btn-outline-success mt-4 py-2 pe-4"
                     href="{% url 'task_manager:position-update' pk=position.id %}"
                  ><i class="fas fa-pen me-1"></i>Edit</a>
                  <a class="btn-outline-danger mt-4 py-2 pe-4"
                     href="{% url 'task_manager:position-delete' pk=position.id %}"
                  ><i class="fas fa-trash me-1"></i>Delete</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>There are no positions yet</p>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/task_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Task List {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3 min-height-600">
    <div class="container w-75">
      <div class="row">
        <div class="col-lg-9">
          <h2 class="mb-3 mt-3">{{ task.name }}</h2>
        </div>
        <div class="col-lg-3 mt-3 text-right">
          <a href="{% url 'task_manager:task-update' pk=task.id %}" class="btn btn-outline-success">
            <i class="fas fa-pen me-1"></i>Edit
          </a>
          <a href="{% url 'task_manager:task-delete' pk=task.id %}" class="btn btn-outline-danger">
            <i class="fas fa-trash me-1"></i>Delete
          </a>
        </div>
      </div>
      <div class="row">
        {% if task.priority == "Urgent" %}
          <p><span class="badge btn-danger">Urgent</span></p>
        {% elif task.priority == "High-priority" %}
          <p><span class="badge btn-warning">High-priority</span></p>
        {% elif task.priority == "Medium-priority" %}
          <p><span class="badge btn-info">Medium-priority</span></p>
        {% elif task.priority == "Low-priority" %}
          <p><span class="badge btn-success">Low-priority</span></p>
        {% endif %}
        <hr>
        <p><i class="fas fa-clipboard me-1"></i>Description: {{ task.description }}</p>
        <p><i class="fas fa-hourglass-half me-1"></i>Deadline: {{ task.deadline|date:"F j, Y" }}</p>
        <p><i class="fas fa-user-friends me-1"></i>Assignees:</p>
        {% for worker in task.assignees.all %}
          <div class="col-lg-3 my-2">
            <div class="card card-plain card-blog bg-gray-300">
              <div class="card-body px-0 m-1 mx-3">
                <a href="{% url 'task_manager:worker-detail' pk=worker.id %}"
                ><h5 class="text-dark font-weight-bold"><i class="fas fa-user-circle me-1"></i>{{ worker.first_name }} {{ worker.last_name }}</h5></a>
                <p><i class="fas fa-id-badge me-1"></i>Position: <b>{{ worker.position.name }}</b></p>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/task_list.html
{% extends 'layouts/base.html' %}

{% block title %} Task List {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <h3>Task List
            <a href="{% url 'task_manager:task-create' %}"
               class="btn btn-outline-success link-to-page ms-3 mt-3">Create task</a>
          </h3>
        </div>
        <div class="col-3 text-right">
          {% include "includes/search_form.html" %}
        </div>
      </div>
      <div class="row">
        {% if task_list %}
          {% for task in task_list %}
            <div class="col-lg-3 col-sm-6 my-2">
              <div class="card card-plain card-blog bg-gradient-faded-white">
                <div class="card-body px-0 m-1 mx-3">
                  {% if task.is_completed %}
                    <p class="btn-outline-success">
                      <i class="fas fa-check-double me-1"></i>Completed
                    </p>
                  {% endif %}
                  <h5>
                    <a href="{% url 'task_manager:task-detail' pk=task.id %}"
                       class="text-dark font-weight-bold">{{ task.name }}</a>
                  </h5>
                  <p>
                    {{ task.description|truncatewords:20 }}
                  </p>
                  {% if task.priority == "Urgent" %}
                    <p><span class="badge btn-danger">Urgent</span></p>
                  {% elif task.priority == "High-priority" %}
                    <p><span class="badge btn-warning">High-priority</span></p>
                  {% elif task.priority == "Medium-priority" %}
                    <p><span class="badge btn-info">Medium-priority</span></p>
                  {% elif task.priority == "Low-priority" %}
                    <p><span class="badge btn-success">Low-priority</span></p>
                  {% endif %}
                  <p>
                    <i class="fas fa-user-friends me-1"></i>Assignees:
                    {% for worker in task.assignees.all %}
                      <a href="{% url 'task_manager:worker-detail' pk=worker.id %}">
                        {{ worker.get_full_name }}{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}
                  </p>
                  <p>
                    <i class="fas fa-calendar me-1"></i>Deadline: {{ task.deadline|date:"d M Y" }}
                  </p>
                  <a href="{% url 'task_manager:task-detail' pk=task.id %}" class="text-info icon-move-right">Details
                    <i class="fas fa-arrow-right text-sm" aria-hidden="true"></i>
                  </a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/task_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p>Are you sure tou want to delete the task type: {{ task_type }}?</p>
  <p><i>All Tasks of this task type will be deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn btn-primary" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
  </form>
{% endblock %}

templates/task_manager/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/tasktype_confirm_delete.html
{% extends 'layouts/base.html' %}

{% block title %} Delete task type {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% load crispy_forms_filters %}
{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-12">
          <h3 class="mt-12">Are you sure you want to delete the task type: {{ tasktype.name }}?</h3>
          <p>All tasks with this type will be deleted!</p>
        </div>
      </div>
      <br>
      <div class="row">
        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Yes, delete" class="btn bg-gradient-danger me-4">
          <a class="btn bg-gradient-success ms-4" href="{{ request.META.HTTP_REFERER }}">Changed my mind</a>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Task List {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3 min-height-600">
    <div class="container w-75">
      <div class="row">
        <div class="col-lg-6">
          <h2 class="mb-3 mt-3">{{ worker.get_full_name }}</h2>
        </div>
        <div class="col-lg-6 mt-3 text-right">
          <a href="{% url 'task_manager:worker-update' pk=worker.id %}" class="btn btn-outline-success">
            <i class="fas fa-pen me-1"></i>Update info
          </a>
          <a href="{% url 'task_manager:worker-delete' pk=worker.id %}" class="btn btn-outline-danger">
            <i class="fas fa-trash me-1"></i>Delete
          </a>
        </div>
      </div>
      <hr>
      <div class="row">
        <p><i class="fas fa-id-badge me-1"></i>Position: {{ worker.position.name }}</p>
        <p><i class="fas fa-at me-1"></i>Email: {{ worker.email }}</p>
        <h4 class="mt-3">Currently working on:</h4>

        {% for task in worker.tasks.all %}
          {% if not task.is_completed %}
            <div class="col-lg-4 col-sm-6 my-2">
              <div class="card card-plain card-blog bg-gradient-faded-white">
                <div class="card-body px-0 m-1 mx-3">
                  <h5>
                    <a href="{% url 'task_manager:task-detail' pk=task.id %}"
                       class="text-dark font-weight-bold">{{ task.name }}</a>
                  </h5>
                  <p>
                    {{ task.description|truncatewords:20 }}
                  </p>
                  {% if task.priority == "Urgent" %}
                    <p><span class="badge btn-danger">Urgent</span></p>
                  {% elif task.priority == "High-priority" %}
                    <p><span class="badge btn-warning">High-priority</span></p>
                  {% elif task.priority == "Medium-priority" %}
                    <p><span class="badge btn-info">Medium-priority</span></p>
                  {% elif task.priority == "Low-priority" %}
                    <p><span class="badge btn-success">Low-priority</span></p>
                  {% endif %}
                  <p>
                    <i class="fas fa-user-friends me-1"></i>Assignees:
                    {% for worker in task.assignees.all %}
                      <a href="{% url 'task_manager:worker-detail' pk=worker.id %}">
                        {{ worker.get_full_name }}{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}
                  </p>
                  <p>
                    <i class="fas fa-calendar me-1"></i>Deadline: {{ task.deadline|date:"d M Y" }}
                  </p>
                  <a href="{% url 'task_manager:task-detail' pk=task.id %}" class="text-info icon-move-right">Details
                    <i class="fas fa-arrow-right text-sm" aria-hidden="true"></i>
                  </a>
                </div>
              </div>
            </div>
          {% else %}
            <p>No tasks are assigned to this employee yet.</p>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/worker_list.html
{% extends 'layouts/base.html' %}

{% block title %} Task List {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation-light.html" %}
  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <h3 class="mb-5">Workers
            <a href="{% url 'task_manager:worker-create' %}"
               class="btn btn-outline-success link-to-page ms-3 mt-3">Create worker</a>
          </h3>
        </div>
        <div class="col-3">
          {% include "includes/search_form.html" %}
        </div>
      </div>

      <div class="row">
        {% if worker_list %}
          <table class="table table-hover align-content-center">
            <tr>
              <th>Full name</th>
              <th>Position</th>
              <th>Username</th>
              <th>Email</th>
            </tr>
            {% for worker in worker_list %}
              <tr>
                <td class="py-3">
                  <a class="py-3" href="{% url 'task_manager:worker-detail' pk=worker.id %}"
                  >{{ worker.get_full_name }} {% if user == worker %}(Me){% endif %}</a>
                </td>
                <td class="py-3">{{ worker.position.name }}</td>
                <td class="py-3"><a class="py-3" href="{% url 'task_manager:worker-detail' pk=worker.id %}"
                >{{ worker.username }}</a></td>
                <td class="py-3">{{ worker.email }}</td>
              </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>There are no workers yet.</p>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}